openapi: 3.0.3
info:
  title: yCloudx - OpenAPI 1.0
  description: |-
    This document defines list of APIs operations that are available from yCloudx. It is only for read-only access.
    
    Some useful links:
    - [yCloudx](https://ycloudx.com)
    - [Lestari Global](https://lestariglob.com)
  version: 1.0.0
servers:
  - url: localhost:8080
tags:
  - name: APIs
    description: Operations for APIs
    # externalDocs:
    #   description: Find out more
    #   url: http://swagger.io
paths:
  /insert_data/vendor:
    post:
      tags:
        - APIs
      summary: Insert work order
      # description: test
      # parameters:
      # - name: accesskey
      #   in: query
      #   description: The asset to be updated
      #   required: true
      #   schema:
      #     type: string
      #     example: Machine
      requestBody:
        description: Add work order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkOrder'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkOrder'          
        '400':
          description: Invalid request format or missing parameters
        '401': 
          description: Authentication failed
        '500':
          description: An unexpected error occured.
  /update_data/vendor:
    post:
      tags:
        - APIs
      summary: Update work order
      # description: test
      requestBody:
        description: Update work order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkOrder'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkOrder'          
        '400':
          description: Invalid request format or missing parameters
        '401': 
          description: Authentication failed
        '500':
          description: An unexpected error occured.
components:
  schemas:
    WorkOrder:
      required:
        - accesskey
        - reported_by
        - system_site
        - location
        - breakdown_date
        - description
      type: object
      properties:
        accesskey:
          type: string
          example: 8276ya2h13g2%dj@ush3#91ofuasd0281
        reported_by:
          type: string
          example: Ali
        system_site:
          type: string
          example: yCloudx
        location:
          type: string
          example: Kuala Lumpur
        section:
          type: string
          example: Room 12
        asset:
          type: string
          example: Machine
        breakdown_date:
          type: string
          format: date
          example: 2024-12-12
        description:
          type: string
          example: Testing
        workorder_type:
          type: string
          example: Daily
